global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
